version: "3"
services:
  bankspringboot:
    container_name: spring_app
    image: bankspringboot
    build: .
    ports:
      - "8001:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: bank
      MYSQL_PORT: 3307
  mysqldb:
    container_name : mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: bank